/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'amit.nahum' at '8/13/17 2:39 PM' with Gradle 3.0
 *
 * @author amit.nahum, @date 8/13/17 2:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
